import 'package:flutter/material.dart';
import 'package:sevaexchange/components/repeat_availability/recurring_listing.dart';
import 'package:sevaexchange/l10n/l10n.dart';
import 'package:sevaexchange/labels.dart';
import 'package:sevaexchange/models/models.dart';
import 'package:sevaexchange/models/request_model.dart';
import 'package:sevaexchange/new_baseline/models/community_model.dart';
import 'package:sevaexchange/ui/screens/home_page/bloc/home_dashboard_bloc.dart';
import 'package:sevaexchange/ui/screens/search/bloc/queries.dart';
import 'package:sevaexchange/ui/screens/search/bloc/search_bloc.dart';
import 'package:sevaexchange/ui/screens/timebank/widgets/timebank_request_card.dart';
import 'package:sevaexchange/utils/bloc_provider.dart';
import 'package:sevaexchange/utils/data_managers/blocs/communitylist_bloc.dart';
import 'package:sevaexchange/utils/helpers/transactions_matrix_check.dart';
import 'package:sevaexchange/utils/utils.dart';
import 'package:sevaexchange/views/core.dart';
import 'package:sevaexchange/views/requests/request_tab_holder.dart';
import 'package:sevaexchange/views/timebank_modules/request_details_about_page.dart';
import 'package:sevaexchange/views/timebanks/widgets/loading_indicator.dart';

class RequestsTabView extends StatelessWidget {
  final CommunityModel communityModel;

  const RequestsTabView({Key? key, required this.communityModel})
      : super(key: key);

  @override
  Widget build(BuildContext mcontext) {
    final _bloc = BlocProvider.of<SearchBloc>(mcontext);
    return Container(
      child: StreamBuilder<String>(
        stream: _bloc!.searchText,
        builder: (context, search) {
          if (search.data == null || search.data == "") {
            return Center(child: Text(S.of(context).search_something));
          }
          return StreamBuilder<List<RequestModel>>(
            stream: Searches.searchRequests(
              queryString: search.data!,
              loggedInUser: _bloc.user!,
              currentCommunityOfUser: _bloc.community!,
            ),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return LoadingIndicator();
              }
              if (snapshot.data == null || snapshot.data!.isEmpty) {
                return Center(
                  child: Text(
                    S.of(context).no_search_result_found,
                  ),
                );
              }

              return ListView.builder(
                padding: EdgeInsets.symmetric(horizontal: 10),
                shrinkWrap: true,
                itemCount: snapshot.data!.length,
                itemBuilder: (context, index) {
                  RequestModel request = snapshot.data![index];
                  return InkWell(
                    onTap: () => _navigateToRequest(
                      context: mcontext,
                      timebankModel: _bloc.timebank!,
                      requestModel: request,
                    ),
                    child: TimebankRequestCard(
                      requestType: request.requestType,
                      isRecurring: request.isRecurring,
                      autoGenerated: request.autoGenerated,
                      photoUrl: request.photoUrl,
                      title: request.title,
                      subtitle: request.description,
                      startTime: request.requestStart,
                      endTime: request.requestEnd,
                      isApplied: request.acceptors!.contains(
                              SevaCore.of(context).loggedInUser.email) ||
                          request.approvedUsers!.contains(
                              SevaCore.of(context).loggedInUser.email) ||
                          false,
                    ),
                  );
                },
              );
            },
          );
        },
      ),
    );
  }

  void _navigateToRequest(
      {BuildContext? context,
      RequestModel? requestModel,
      TimebankModel? timebankModel}) {
    var isAdmin;
    if (requestModel!.requestMode == RequestMode.PERSONAL_REQUEST) {
      isAdmin = requestModel.sevaUserId ==
          SevaCore.of(context!).loggedInUser.sevaUserID;
    } else {
      isAdmin = isAccessAvailable(
          timebankModel!, SevaCore.of(context!).loggedInUser.sevaUserID!);
    }

    if (requestModel.isRecurring!) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => RecurringListing(
              requestModel: requestModel,
              offerModel: null,
              timebankModel: timebankModel,
              comingFrom: ComingFrom.Requests),
        ),
      );
    } else {
      if (requestModel.sevaUserId ==
              SevaCore.of(context).loggedInUser.sevaUserID ||
          isAccessAvailable(
              timebankModel!, SevaCore.of(context).loggedInUser.sevaUserID!)) {
        timeBankBloc.setSelectedRequest(requestModel);
        timeBankBloc.setSelectedTimeBankDetails(timebankModel);
        timeBankBloc.setIsAdmin(isAdmin);
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_context) => BlocProvider(
              bloc:
                  HomeDashBoardBloc(), // Create new instance instead of trying to access existing one
              child: RequestTabHolder(
                isAdmin: true,
                communityModel: communityModel,
              ),
            ),
          ),
        );
      } else {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_context) => BlocProvider(
              bloc:
                  HomeDashBoardBloc(), // Create new instance instead of trying to access existing one
              child: RequestDetailsAboutPage(
                requestItem: requestModel,
                timebankModel: timebankModel,
                isAdmin: false,
                communityModel: communityModel,
                //  project_id: '',
              ),
            ),
          ),
        );
      }
    }
  }
}
