import 'package:flutter/material.dart';
import 'package:sevaexchange/l10n/l10n.dart';
import 'package:sevaexchange/views/onboarding/interests_view.dart';

///Create an instance with the default constructor to use the default list of English profanity.
/// Use the other constructors to customize the profanity list.
class ProfanityDetector {
  static Widget getProanityAdvisory({
    required String suggestion,
    required SuggestionMode suggestionMode,
    required BuildContext context,
  }) {
    return Padding(
      padding: const EdgeInsets.all(10.0),
      child: Container(
          height: 80,
          alignment: Alignment.centerLeft,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    RichText(
                      text: TextSpan(
                        children: <TextSpan>[
                          TextSpan(
                            text: "Cannot add ",
                            style: TextStyle(
                              color: Colors.red,
                            ),
                          ),
                          TextSpan(
                            text: "\"${suggestion}\"",
                            style: TextStyle(
                              fontSize: 16,
                              color: Colors.red,
                              decoration: TextDecoration.underline,
                              decorationColor: Colors.red,
                              decorationStyle: TextDecorationStyle.wavy,
                              decorationThickness: 1.5,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Text(
                      S.of(context).profanity_text_alert,
                      style: TextStyle(
                        fontSize: 16,
                        color: Colors.grey,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          )),
    );
  }

  List<String> defaultWordsToFilterOutList = [
    '2g1c',
    '2 girls 1 cup',
    'acrotomophilia',
    'alabama hot pocket',
    'alaskan pipeline',
    'anal',
    'anilingus',
    'anus',
    'apeshit',
    'arsehole',
    'ass',
    'asshole',
    'assmunch',
    'auto erotic',
    'autoerotic',
    'babeland',

    'baby batter',
    'baby juice',
    'ball gag',
    'ball gravy',
    'ball kicking',
    'ball licking',
    'ball sack',
    'ball sucking',
    'bangbros',
    'bareback',
    'barely legal',
    'barenaked',
    'bastard',
    'bastardo',
    'bastinado',
    'bbw',
    'bdsm',
    'beaner',
    'beaners',
    'beaver cleaver',
    'beaver lips',
    'bestiality',
    'big black',
    'big breasts',
    'big knockers',
    'big tits',
    'bimbos',
    'birdlock',
    'bitch',
    'bitches',
    'black cock',
    'blonde action',
    'blonde on blonde action',
    'blowjob',
    'blow job',
    'blow your load',
    'blue waffle',
    'blumpkin',
    'bollocks',
    'bondage',
    'boner',
    'boob',
    'boobs',
    'booty call',
    'brown showers',
    'brunette action',
    'bukkake',
    'bulldyke',
    'bullet vibe',
    'bullshit',
    'bung hole',
    'bunghole',
    'busty',
    'butt',
    'buttcheeks',
    'butthole',
    'camel toe',
    'camgirl',
    'camslut',
    'camwhore',
    'carpet muncher',
    'carpetmuncher',
    'chocolate rosebuds',
    'circlejerk',
    'cleveland steamer',
    'clit',
    'clitoris',
    'clover clamps',
    'clusterfuck',
    'cock',
    'cocks',
    'coprolagnia',
    'coprophilia',
    'cornhole',
    'coon',
    'coons',
    'creampie',
    'cum',
    'cumming',
    'cunnilingus',
    'cunt',
    'darkie',
    'date rape',
    'daterape',
    'deep throat',
    'deepthroat',
    'dendrophilia',
    'dick',
    'dildo',
    'dingleberry',
    'dingleberries',
    'dirty pillows',
    'dirty sanchez',
    'doggie style',
    'doggiestyle',
    'doggy style',
    'doggystyle',
    'dog style',
    'dolcett',
    'domination',
    'dominatrix',
    'dommes',
    'donkey punch',
    'double dong',
    'double penetration',
    'dp action',
    'dry hump',
    'dvda',
    'eat my ass',
    'ecchi',
    'ejaculation',
    'erotic',
    'erotism',
    'escort',
    'eunuch',
    'faggot',
    'fecal',
    'felch',
    'fellatio',
    'feltch',
    'female squirting',
    'femdom',
    'figging',
    'fingerbang',
    'fingering',
    'fisting',
    'foot fetish',
    'footjob',
    'frotting',
    'fuck',
    'fucker',
    'fuckers',
    'fucked',
    'fucked up',
    'fuckedup',
    'fuck buttons',
    'fuckin',
    'fucking',
    'fucktards',
    'fudge packer',
    'fudgepacker',
    'futanari',
    'gang bang',
    'gay sex',
    'genitals',
    'giant cock',
    'girl on',
    'girl ontop',
    'girls gone wild',
    'goatcx',
    'goatse',
    'god damn',
    'gokkun',
    'golden shower',
    'goodpoop',
    'goo girl',
    'goregasm',
    'grope',
    'group sex',
    'g-spot',
    'guro',
    'hand job',
    'handjob',
    'hard core',
    'hardcore',
    'hentai',
    'homoerotic',
    'honkey',
    'hooker',
    'hot carl',
    'hot chick',
    'how to kill',
    'how to murder',
    'huge fat',
    'humping',
    'incest',
    'intercourse',
    'jack off',
    'jail bait',
    'jailbait',
    'jelly donut',
    'jerk off',
    'jigaboo',
    'jiggaboo',
    'jiggerboo',
    'jizz',
    'juggs',
    'kike',
    'kinbaku',
    'kinkster',
    'kinky',
    'knobbing',
    'leather restraint',
    'leather straight jacket',
    'lemon party',
    'lolita',
    'lovemaking',
    'make me come',
    'male squirting',
    'masturbate',
    'menage a trois',
    'milf',
    'missionary position',
    'motherfucker',
    'mound of venus',
    'mr hands',
    'muff diver',
    'muffdiving',
    'nambla',
    'nawashi',
    'negro',
    'neonazi',
    'nigga',
    'nigger',
    'nig nog',
    'nimphomania',
    'nipple',
    'nipples',
    'nsfw images',
    'nude',
    'nudity',
    'nympho',
    'nymphomania',
    'octopussy',
    'omorashi',
    'one cup two girls',
    'one guy one jar',
    'orgasm',
    'orgy',
    'paedophile',
    'paki',
    'panties',
    'panty',
    'pedobear',
    'pedophile',
    'pegging',
    'penis',
    'phone sex',
    'piece of shit',
    'pissing',
    'piss pig',
    'pisspig',
    'playboy',
    'pleasure chest',
    'pole smoker',
    'ponyplay',
    'poof',
    'poon',
    'poontang',
    'punany',
    'poop chute',
    'poopchute',
    'porn',
    'porno',
    'pornography',
    'prince albert piercing',
    'pthc',
    'pubes',
    'pussy',
    'queaf',
    'queef',
    'quim',
    'raghead',
    'raging boner',
    'rape',
    'raping',
    'rapist',
    'rectum',
    'reversecowgirl',
    'rimjob',
    'rimming',
    'rosy palm',
    'rosy palm and her 5 sisters',
    'rusty trombone',
    'sadism',
    'santorum',
    'scat',
    'schlong',
    'scissoring',
    'semen',
    'sex',
    'sexo',
    'sexy',
    'shaved beaver',
    'shaved pussy',
    'shemale',
    'shibari',
    'shit',
    'shitblimp',
    'shitty',
    'shota',
    'shrimping',
    'skeet',
    'slanteye',
    'slut',
    's&m',
    'smut',
    'snatch',
    'snowballing',
    'sodomize',
    'sodomy',
    'spic',
    'splooge',
    'splooge moose',
    'spooge',
    'spread legs',
    'spunk',
    'strap on',
    'strapon',
    'strappado',
    'strip club',
    'style doggy',
    'suck',
    'sucks',
    'suicide girls',
    'sultry women',
    'swastika',
    'swinger',
    'tainted love',
    'taste my',
    'tea bagging',
    'threesome',
    'throating',
    'tied up',
    'tight white',
    'tit',
    'tits',
    'titties',
    'titty',
    'tongue in a',
    'topless',
    'tosser',
    'towelhead',
    'tranny',
    'tribadism',
    'tub girl',
    'tubgirl',
    'tushy',
    'twat',
    'twink',
    'twinkie',
    'two girls one cup',
    'undressing',
    'upskirt',
    'urethra play',
    'urophilia',
    'vagina',
    'venus mound',
    'vibrator',
    'violet wand',
    'vorarephilia',
    'voyeur',
    'vulva',
    'wank',
    'wetback',
    'wet dream',
    'white power',
    'wrapping men',
    'wrinkled starfish',
    'xx',
    'xxx',
    'yaoi',
    'yellow showers',
    'yiffy',
    'zoophilia',
    '🖕',
    //additional
    'arse',
    'ballsack',
    'biatch',
    'bloody',
    'blow job',
    'bollock',
    'bollok',
    'bugger',
    'bum',
    'buttplug',
    'crap',
    'damn',
    'dyke',
    'fag',
    'fellate',
    'felching',
    'f u c k',
    'fudge packer',
    'flange',
    'Goddamn',
    'homo',
    'jerk',
    'knobend',
    'knob end',
    'labia',
    'lmao',
    'lmfao',
    'muff',
    'piss',
    'poop',
    'prick',
    'pube',
    'queer',
    'scrotum',
    's hit',
    'sh1t',
    'smegma',
    'turd',
    'twat',
    'whore',
    'wtf',
    //spanish

    '2 chicas 1 taza',
    'acrotomofilia',
    'Alabama bolsillo caliente',
    'oleoducto de Alaska',
    'anal',
    'Anilingus',
    'ano',
    'culo',
    'Estúpido',
    'auto erótica',
    'bebé bateador',
    'jugo de bebé',
    'bola de la mordaza',
    'bola de la salsa',
    'bola de patadas',
    'Pelota lamiendo',
    'bola de saco',
    'Chupada de huevos',
    'a pelo',
    'apenas legal',
    'Bastardo',
    'bastardo',
    'bastinado',
    'Beaver Cleaver',
    'los labios de castor',
    'bestialidad',
    'grande y negro',
    'pechos grandes',
    'tetas grandes',
    'grandes tetas',
    'perra',
    'perras',
    'gallo negro',
    'acción rubio',
    'rubia en la acción rubio',
    'mamada',
    'sonarse la carga',
    'mamada',
    'galleta azul',
    'cojones',
    'esclavitud',
    'metedura de pata',
    'teta',
    'tetas',
    'booty call',
    'duchas, marrones',
    'acción Morena',
    'bukkake',
    'bala vibración',
    'mierda',
    'agujero del tapón',
    'boca de tonel',
    'tetona',
    'extremo',
    'Butthole',
    'dedo de camello',
    'alfombra muncher',
    'capullos de rosa de chocolate',
    'vapor de Cleveland',
    'clítoris',
    'clítoris',
    'abrazaderas de trébol',
    'polla',
    'gallos',
    'mapache',
    'Coons',
    'Coprofilia',
    'chorreo de leche',
    'semen',
    'correrse',
    'Con la lengua',
    'coño',
    'Fecha violación',
    'Garganta profunda',
    'Garganta profunda',
    'polla',
    'consolador',
    'almohadas sucias',
    'Sánchez sucio',
    'estilo perro',
    'estilo perrito',
    'estilo perrito',
    'dominación',
    'dominatrix',
    'Donkey Punch',
    'dong doble',
    'doble penetración',
    'acción dp',
    'joroba seco',
    'comer mi culo',
    'eyaculación',
    'erótico',
    'erotismo',
    'escolta',
    'eunuco',
    'maricón',
    'fecal',
    'felación',
    'corrida femenina',
    'dominación femenina',
    'digitación',
    'Puño',
    'fetichismo del pie',
    'Trabajando con el pie',
    'Fuck Buttons',
    'Mierda',
    'puto',
    'maldito',
    'fudge packer',
    'Futanari',
    'Punto G',
    'Gang Bang',
    'sexo gay',
    'genitales',
    'polla gigante',
    'chica en',
    'niña en la cima',
    'girls gone wild',
    'la maldición del dios',
    'gokkun',
    'baño de oro',
    'goo chica',
    'ir a tientas',
    'sexo en grupo',
    'guro',
    'trabajo de la mano',
    'Masturbación con la mano',
    'núcleo duro',
    'duro',
    'hentai',
    'homoerótico',
    'puta',
    'Carl caliente',
    'hot chick',
    'cómo matar',
    'cómo matar',
    'enorme de grasa',
    'follar',
    'incesto',
    'coito',
    'masturbar',
    'cárcel cebo',
    'jailbait',
    'jalea rosquilla',
    'hacerse una paja',
    'semen',
    'pozo',
    'rizado',
    'la restricción de cuero',
    'cuero camisa de fuerza',
    'limón partido',
    'lolita',
    'haciendo el amor',
    'Hazme llegar',
    'eyaculatorio masculino',
    'masturbarse',
    'tríos',
    'MILF',
    'posición del misionero',
    'hijo de puta',
    'monte de Venus',
    'mr manos',
    'Buceador del manguito',
    'negro',
    'negro',
    'negro',
    'pezón',
    'pezones',
    'nsfw imágenes',
    'desnudo',
    'desnudez',
    'ninfómana',
    'ninfomanía',
    'Octopussy',
    'una taza de dos niñas',
    'un chico un frasco',
    'orgasmo',
    'orgía',
    'pedófilo',
    'paquistaní',
    'bragas',
    'bragas',
    'pedófilo',
    'vinculación',
    'pene',
    'sexo telefónico',
    'pedazo de mierda',
    'orina de cerdo',
    'meando',
    'playboy',
    'placer pecho',
    'polo del fumador',
    'maricón',
    'Poon',
    'caca chute',
    'pornografía',
    'pornografía',
    'pornografía',
    'Príncipe Alberto perforación',
    'pthc',
    'pubis',
    'coño',
    'Quim',
    'embravecido erección',
    'violación',
    'violar',
    'violador',
    'recto',
    'beso negro',
    'color de rosa de palma y sus hermanas 5',
    'palma de color de rosa',
    'trombón oxidado',
    'sadismo',
    'santorum',
    'tijera',
    'semen',
    'sexo',
    'sexy',
    'castor afeitado',
    'coño afeitado',
    'transexual',
    'mierda',
    'de mierda',
    'Shota',
    'camaronero',
    'tiro al plato',
    'puta',
    'tizón',
    'arrebatar',
    'bola de nieve',
    'sodomizar',
    'sodomía',
    'spic',
    'piernas abiertas',
    'agallas',
    'sujetar con correa',
    'strappado',
    'Strip Club',
    'perrito',
    'chupar',
    'chupa',
    'chicas suicidas',
    'sensual mujer',
    'esvástica',
    'mundano',
    'Amor podrido',
    'el sabor de mi',
    'té embolsado',
    'grupo de tres',
    'Tragar',
    'atado',
    'blanca ajustada',
    'teta',
    'tetas',
    'tetas',
    'teta',
    'lengua en a',
    'top-less',
    'transexual',
    'tribadism',
    'bañera de niña',
    'tubgirl',
    'tushy',
    'coño',
    'fulanita',
    'dos muchachas una taza',
    'desvestirse',
    'upskirt',
    'juego uretra',
    'vagina',
    'venus montículo',
    'vibrador',
    'varita violeta',
    'vorarefilia',
    'voyeur',
    'vulva',
    'hacerse una paja',
    'sueño húmedo',
    'espalda mojada',
    'poder blanco',
    'envolver los hombres',
    'estrellas de mar arrugada',
    'duchas amarillas',
    'zoofilia',
    //portugeese
    '2 meninas um copo',
    'acrotomophilia',
    'Alabama Hot Pocket',
    'oleoduto do Alasca',
    'anal',
    'anilingus',
    'ânus',
    'bunda',
    'Idiota',
    'auto erótico',
    'bebê massa',
    'suco de baby',
    'mordaça de bola',
    'gravy bola',
    'bola chutando',
    'lamber bola',
    'saco bola',
    'sucção bola',
    'bareback',
    'Barely Legal',
    'Desgraçado',
    'bastardo',
    'bastinado',
    'cutelo castor',
    'lábios castor',
    'bestialidade',
    'grande Preto',
    'seios grandes',
    'grandes batedores',
    'peitos grandes',
    'cadela',
    'cadelas',
    'galo negro',
    'ação loira',
    'loira em ação loira',
    'blow job',
    'explodir sua carga',
    'boquete',
    'waffle azul',
    'besteira',
    'escravidão',
    'tesão',
    'do boob',
    'peitos',
    'booty call',
    'chuveiros marrom',
    'ação morena',
    'bukkake',
    'vibração bala',
    'besteira',
    'bung hole',
    'bunghole',
    'peituda',
    'bunda',
    'butthole',
    'camelo toe',
    'tapete muncher',
    'botões de rosas de chocolate',
    'Navio de Cleveland',
    'clit',
    'clitóris',
    'braçadeiras trevo',
    'galo',
    'cocks',
    'coon',
    'Coons',
    'coprofilia',
    'Creampie',
    'porra',
    'gozando',
    'cunnilingus',
    'cunt',
    'estupro',
    'garganta Profunda',
    'garganta Profunda',
    'pau',
    'dildo',
    'travesseiros sujos',
    'sanchez sujo',
    'estilo cachorro',
    'estilo cachorrinho',
    'estilo cachorrinho',
    'dominação',
    'dominatrix',
    'soco burro',
    'duplo dong',
    'dupla penetração',
    'ação dp',
    'corcunda seca',
    'comer minha bunda',
    'ejaculação',
    'erótico',
    'erotismo',
    'escolta',
    'eunuco',
    'bicha',
    'fecal',
    'fellatio',
    'esguichando feminino',
    'femdom',
    'dedilhado',
    'o fisting',
    'fetiche por pés',
    'com os pes',
    'botões foda',
    'Porra',
    'porra',
    'porra',
    'fudge packer',
    'futanari',
    'ponto G',
    'gang bang',
    'sexo gay',
    'órgãos genitais',
    'galo gigante',
    'girl on',
    'menina no topo',
    'Girls Gone Wild',
    'Maldito',
    'Gokkun',
    'chuveiro dourado',
    'goo girl',
    'grope',
    'sexo em grupo',
    'guro',
    'trabalho de mão',
    'Masturbação',
    'núcleo duro',
    'hardcore',
    'hentai',
    'homoerótica',
    'prostituta',
    'hot carl',
    'pintainho quente',
    'como matar',
    'como matar',
    'enorme de gordura',
    'transar',
    'incesto',
    'coito',
    'punheta',
    'Jail Bait',
    'jailbait',
    'geleia de donut',
    'bate uma',
    'porra',
    'Kike',
    'anormal',
    'contenção de couro',
    'revestimento de couro linear',
    'limão partido',
    'lolita',
    'fazer amor',
    'Me faça vir',
    'esguichando masculino',
    'masturbar',
    'ménage à trois',
    'Milf',
    'posição Missionaria',
    'filho da puta',
    'monte de Vênus',
    'mr mãos',
    'mergulhador regalo',
    'negro',
    'nigga',
    'negro',
    'mamilo',
    'mamilos',
    'imagens nsfw',
    'nu',
    'nudez',
    'ninfomaníaca',
    'ninfomania',
    'Octopussy',
    'um copo duas meninas',
    'um cara um jar',
    'orgasmo',
    'orgia',
    'pedófilo',
    'paki',
    'calcinhas',
    'calcinha',
    'pedófilo',
    'pegging',
    'pênis',
    'sexo por telefone',
    'pedaço de merda',
    'mijo de porco',
    'mijando',
    'Playboy',
    'peito prazer',
    'pólo fumante',
    'poof',
    'poon',
    'cocô rampa',
    'pornô',
    'porno',
    'pornografia',
    'príncipe Albert perfuração',
    'pthc',
    'pubes',
    'bichano',
    'Quim',
    'furiosa tesão',
    'estupro',
    'estuprar',
    'estuprador',
    'reto',
    'rimming',
    'rosado palma e seus 5 irmãs',
    'palma rosada',
    'trombone enferrujado',
    'sadismo',
    'Santorum',
    'tesoura',
    'sêmen',
    'sexo',
    'sexy',
    'castor raspado',
    'buceta raspada',
    'transsexual',
    'merda',
    'merda',
    'Shota',
    'shrimping',
    'skeet',
    'vagabunda',
    'smut',
    'arrebatar',
    'bola de neve',
    'sodomizar',
    'sodomia',
    'spic',
    'pernas abertas',
    'coragem',
    'cinta em'
        'strappado',
    'strip club',
    'Doggy Style',
    'chupar',
    'é uma merda',
    'Suicide Girls',
    'mulheres sensuais',
    'suástica',
    'swinger',
    'amor estragado',
    'provar a minha',
    'ensacamento chá',
    'threesome',
    'Garganta',
    'amarrado',
    'branco apertado',
    'tit',
    'tits',
    'peitos',
    'maminha',
    'língua em um',
    'em topless',
    'travesti',
    'tribadism',
    'tub girl',
    'tubgirl',
    'tushy',
    'pentelho',
    'twinkie',
    'duas meninas um copo',
    'despindo',
    'upskirt',
    'jogo uretra',
    'vagina',
    'venus montículo',
    'vibrador',
    'violeta varinha',
    'vorarefilia',
    'voyeur',
    'vulva',
    'punheta',
    'sonho molhado',
    'wetback',
    'Poder branco',
    'homens acondicionamento',
    'Starfish enrugada',
    'chuveiros amarelos',
    'zoofilia',
    //french
    '2 filles 1 tasse',
    'Acrotomophilia',
    'alabama de poche à chaud',
    'pipeline alaska',
    'anal',
    'anilingus',
    'anus',
    'cul',
    'Connard',
    'érotique auto',
    'bébé pâte',
    'bébé jus',
    'gag de balle',
    'sauce ballon',
    'coups de pied balle',
    'léchage  de balle',
    'sac de ballo',
    'balle sucer',
    'à cru',
    'À peine légal',
    'Connard',
    'Bastardo',
    'bastonnade',
    'couperet du castor',
    'les lèvres de castor',
    'bestialité',
    'grand noir',
    'gros seins',
    'grands heurtoirs',
    'gros seins',
    'chienne',
    'chiennes',
    'coq noir',
    'laction blond',
    'blonds blonds sur laction',
    'le travail de coup',
    'souffler votre charge',
    'blowjob',
    'gaufres bleu',
    'Bollocks',
    'esclavage',
    'gaffe',
    'boob',
    'seins',
    'appel \' butin',
    'douches brun',
    'l\'action brune',
    'bukkake',
    'ambiance bullet',
    'connerie',
    'bonde',
    'bunghole',
    'gros seins',
    'bout',
    'Butthole',
    'camel toe',
    'tapis muncher',
    'rosebuds chocolat',
    'vapeur cleveland',
    'clito',
    'clitoris',
    'pinces trèfle',
    'coq',
    'coqs',
    'nègre',
    'Coons',
    'coprophilie',
    'Creampie',
    'sperme',
    'Cumming',
    'Cunnilingus',
    'chatte',
    'viol date',
    'gorge Profonde',
    'gorge Profonde',
    'queue',
    'godemiché',
    'oreillers sales',
    'sanchez \' sale',
    'à la manière d\'un chien',
    'doggie style',
    'Chien',
    'domination',
    'dominatrix',
    'poinçon âne',
    'double-dong',
    'double pénétration',
    'dp action',
    'bosse sèche',
    'manger mon cul',
    'éjaculation',
    'érotique',
    'Erotisme',
    'escorte',
    'eunuque',
    'fagot',
    'fécale',
    'fellations',
    'Jouir femme',
    'Dominatrice',
    'doigté',
    'fist',
    'fétichisme des pieds',
    'footjob',
    'boutons fuck',
    'Merde',
    'fuckin',
    'putain de',
    'packer fudge',
    'futanari',
    'g-spot',
    'gang bang',
    'sexe \' gay',
    'organes génitaux',
    'coq \' géant',
    'fille sur',
    'fille au dessus',
    'filles gone wild',
    'putain de Dieu',
    'Gokkun',
    'douche d\'or',
    'goo fille',
    'tâtonner',
    'le sexe \' du groupe',
    'Guro',
    'branlette',
    'branlette',
    'noyau dur',
    'Hardcore',
    'hentai',
    'homoérotique',
    'talonneur',
    'chaud carl',
    'poussin chaud',
    'comment tuer',
    'comment assassiner',
    'énorme gras',
    'humping',
    'inceste',
    'rapports',
    'jack off',
    'appât prison',
    'jailbait',
    'donut gelée',
    'se branler',
    'sperme',
    'Kike',
    'crépus',
    'retenue en cuir',
    'Veste en cuir de droite',
    'citron partie',
    'lolita',
    'faire l\'amour',
    'me faire venir',
    'gicler mâle',
    'masturber',
    'menage a trois',
    'MILF',
    'position du missionaire',
    'connard',
    'monticule de vénus',
    'mains, M',
    'muff plongeur',
    'nègre',
    'nigga',
    'nègre',
    'téton',
    'mamelons',
    'images nsfw,     nu',
    'nudité',
    'nympho',
    'nymphomanie',
    'Octopussy',
    'deux filles une tasse',
    'un pot \' un gars',
    'orgasme',
    'orgie',
    'pédophile',
    'paki',
    'culotte',
    'culotte',
    'pédophile',
    'chevillage',
    'pénis',
    'le sexe de téléphone',
    'merde',
    'pisse cochon',
    'pisser',
    'playboy',
    'poitrine de plaisir',
    'pôle fumeur',
    'tapette',
    'Poon',
    'caca chute',
    'porno',
    'porno',
    'pornographie',
    'Prince Albert perçage',
    'pthc',
    'pubis',
    'chatte',
    'Quim',
    'qui fait rage Boner',
    'râpé',
    'avoir violé',
    'violeur',
    'rectum',
    'anulingus',
    'paume rose et ses 5 sœurs',
    'paume rose',
    'trombone \' rouillé',
    'sadisme',
    'santorum',
    'scissoring',
    'sperme',
    'sexe',
    'sexy',
    'castor rasé',
    'chatte rasée',
    'transexuelle',
    'merde',
    'merdique',
    'Shota',
    'shrimping',
    'ball-trap',
    'salope',
    'cochonneries',
    'arracher',
    'boule de neige',
    'sodomiser',
    'sodomie',
    'SPIC',
    'écarter les jambes',
    'cran',
    'sangle sur',
    'estrapade',
    'bande club',
    'doggy style',
    'sucer',
    'sucks',
    'filles de suicide',
    'les femmes étouffantes',
    'svastika',
    'échangiste',
    'un amour entaché',
    'le goût de mon',
    'ensachage de thé',
    'trio',
    'throating',
    'attaché',
    'blanc serré',
    'mésange',
    'seins',
    'nichons',
    'Titty',
    'la langue dans un',
    'aux seins nus',
    'Travesti',
    'tribadisme',
    'baignoire fille',
    'tubgirl',
    'tushy',
    'chatte',
    'twinkie',
    'deux filles une tasse',
    'déshabillage',
    'upskirt',
    'jeu de l\'urètre',
    'vagin',
    'vénus monticule',
    'vibreur',
    'Baguette \' violet',
    'vorarephilie',
    'voyeur',
    'vulve',
    'branler',
    'rêve \'humide',
    'wetback',
    'pouvoir blanc',
    'hommes d\'emballage',
    'étoile de mer ridée',
    'douches jaune',
    'zoophilie',

    //chineese
    '两名女一杯',
    '慕残',
    '阿拉巴马热口袋',
    '阿拉斯加管道',
    '肛门',
    '舔肛',
    '肛门',
    '屁股',
    '混蛋',
    '汽车情色',
    '宝宝连击',
    '婴儿喝果汁',
    '球插科打诨',
    '球肉汁',
    '踢球',
    '球舔',
    '球袋',
    '球吸吮',
    '无鞍',
    '勉强法律',
    '混蛋',
    '巴斯塔',
    '杖',
    '海狸切肉刀',
    '海狸嘴唇',
    '兽性',
    '大黑',
    '波霸',
    '坦胸露乳',
    '大奶',
    '母狗',
    '母狗',
    '黑公鸡',
    '金发行动',
    '金发碧眼金发碧眼的上行动',
    '口交',
    '吹你的负荷',
    '口交',
    '蓝华夫饼',
    '胡说',
    '束缚',
    '蠢蛋',
    '布布',
    '胸部',
    '性邀请',
    '棕色阵雨',
    '黑发行动',
    '颜射',
    '子弹盛传',
    '废话',
    '塞孔',
    '瓶口',
    '丰满',
    '屁股',
    '屁眼',
    '骆驼趾',
    '地毯muncher',
    '巧克力玫瑰花蕾',
    '克利夫兰蒸笼',
    '阴蒂',
    '阴蒂',
    '三叶草夹',
    '公鸡',
    '公鸡',
    '浣熊',
    '浣熊',
    '粪便嗜好症',
    '中出',
    '暨',
    '卡明',
    '舔阴',
    '屄',
    '约会强奸',
    '深喉咙',
    '深喉咙',
    '家伙',
    '假阳具',
    '脏的枕头',
    '肮脏的桑切斯',
    '狗的风格',
    '小狗式',
    '狗的风格',
    '统治',
    '母夜叉',
    '驴打孔',
    '双东',
    '双重穿透',
    'DP行动',
    '干驼峰',
    '吃我的屁股',
    '射精',
    '情色',
    '性的兴奋',
    '护送',
    '宦官',
    '柴草',
    '粪',
    '口交',
    '女喷气',
    '调教',
    '指法',
    '拳打',
    '恋足',
    '脚交',
    '他妈的按钮',
    '他妈的',
    '该死的',
    '他妈的',
    '软糖包装机',
    '扶他那里',
    'G点',
    '帮派砰',
    '同性恋',
    '生殖器',
    '巨大的公鸡',
    '女孩',
    'ontop的女孩',
    '女孩狂野',
    '该死',
    '饮精',
    '金雨',
    '咕女孩',
    '摸索',
    '集体性交',
    '九老',
    '手工作',
    '灰机',
    '硬核',
    '铁杆',
    '漫画',
    '同性恋',
    '妓女',
    '热卡尔',
    '辣妹',
    '怎么杀',
    '如何杀害',
    '巨大的脂肪',
    '驼峰',
    '乱伦',
    '交往',
    '打手枪',
    '监狱诱饵',
    '祸水妞',
    '果冻甜甜圈',
    '挺举关闭',
    '每次妳站在',
    '基科',
    '淫',
    '皮革克制',
    '皮夹克直',
    '柠檬党',
    '洛丽塔',
    '做爱',
    '让我来',
    '男性喷气',
    '手淫',
    '三角家庭',
    '摩洛伊斯兰解放阵线',
    '传教士体位',
    '娘',
    '金星丘',
    '先生手中',
    '耳罩潜水者',
    '黑人',
    '黑鬼',
    '黑鬼',
    '乳头',
    '乳头',
    'NSFW图像',
    '裸体',
    '裸露',
    '慕男狂',
    '色情狂',
    '八爪女',
    '一杯两个女孩',
    '一个人一个坛子',
    '性高潮',
    '狂欢',
    '恋童癖',
    '帕基',
    '内裤',
    '内裤',
    '恋童癖',
    '挂',
    '阴茎',
    '手机色情',
    '屁',
    '小便猪',
    '撒尿',
    '花花公子',
    '快乐的胸部',
    '极吸烟者',
    '噗',
    '胡桐',
    '船尾滑道',
    'A片',
    '色情',
    '色情',
    '阿尔伯特亲王刺入',
    '幼幼',
    '阴毛',
    '猫',
    '奎姆',
    '肆虐的大错',
    '强奸',
    '强奸',
    '强奸犯',
    '直肠',
    '沸腾',
    '玫瑰色的手掌上和她的姐妹5',
    '玫瑰色的手掌上',
    '生锈的长号',
    '虐待狂',
    '桑托伦',
    '剪式',
    '精液',
    '性别',
    '性感',
    '剃海狸',
    '剃光猫',
    '人妖',
    '拉屎',
    '低劣',
    '翔太',
    '捕虾',
    '双向飞碟',
    '贱人',
    '黑穗病',
    '抢夺',
    '滚雪球',
    '鸡奸',
    '鸡奸',
    '穗',
    '传播腿',
    '胆量',
    '背带上',
    '吊刑',
    '条俱乐部',
    '风格狗',
    '吸',
    '吮吸',
    '自杀女孩',
    '撩人的女性',
    '卍',
    '扫平',
    '肮脏的爱',
    '品尝我的',
    '茶叶装袋',
    '三人组',
    '除水器',
    '绑起来',
    '白色紧身',
    '山雀',
    '山雀',
    '奶子',
    '奶',
    '舌头在',
    '赤裸上身',
    '变性人',
    '交叉体位',
    '浴缸女孩',
    'tubgirl',
    '小屁屁',
    '娘们',
    '小女生',
    '两个女孩一个杯',
    '脱衣',
    '掀裙',
    '尿道戏',
    '阴道',
    '金星丘',
    '振动器',
    '紫魔杖',
    '食用性兴奋',
    '偷窥',
    '外阴',
    '手淫',
    '梦遗',
    '回潮',
    '白电',
    '包装男人',
    '皱海星',
    '黄雨',
    '动物恋',

    //
  ];
  List<String> wordsToFilterList = [];

  ///Created to filter with a list containing only the words provided in the list  provided by user[badWordsList].
  ProfanityDetector.filterOnly(List<String> badWordsList) {
    this.wordsToFilterList = badWordsList;
  }

  ///Creates a filter with the default list of profanity, excluding the words in [ignoreList].
  ///
  ///As the default list may also singular and plural forms, please provide as many word variations as possible.
  ProfanityDetector.ignore(List<String> ignoreList) {
    this.wordsToFilterList = this.defaultWordsToFilterOutList;
    ignoreList.forEach((word) {
      this.wordsToFilterList.remove(word);
    });
  }

  ///Creates a filter with a list containing the default English words and the additional words provided in [badWordsList].
  ProfanityDetector.filterAdditionally(List<String> badWordsList) {
    this.wordsToFilterList = [
      ...this.defaultWordsToFilterOutList,
      ...badWordsList
    ];
  }

  ///Creates a filter with the default list of profanity.
  ProfanityDetector() {
    this.wordsToFilterList = this.defaultWordsToFilterOutList;
  }

  ///Returns `true` if [inputString] has profanity, else false.
  bool isProfaneString(String inputString) {
    bool isProfane = false;
    this.wordsToFilterList.forEach((word) {
      if (inputString.toLowerCase().split(' ').contains(word)) {
        isProfane = true;
      }
    });
    return isProfane;
  }

  ///Returns a censored version of the [inputString], with asterisk (*) pattern as default.
  ///
  ///If [replaceWith] is provided, replaces all profane words to that [replaceWith] string.
  String censorString(String inputString, {String? replaceWith}) {
    List<String> inputStringSoup = inputString.split(' ');
    this.wordsToFilterList.forEach((word) {
      if (replaceWith == null) {
        for (int i = 0; i < inputStringSoup.length; i++) {
          if (inputStringSoup[i].toLowerCase() == word) {
            inputStringSoup[i] = '*' * word.length;
          }
        }
      } else {
        for (int i = 0; i < inputStringSoup.length; i++) {
          if (inputStringSoup[i].toLowerCase() == word) {
            inputStringSoup[i] = replaceWith;
          }
        }
      }
    });
    return inputStringSoup.join(' ');
  }

  ///Returns a list of all profanity found in the string.
  List<String> getAllProfanityFoundInSentence(String inputString) {
    List<String> found = [];
    this.wordsToFilterList.forEach((word) {
      if (inputString.toLowerCase().contains(word)) {
        found.add(word);
      }
    });
    return found;
  }
}
