import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:intl/intl.dart';
import 'package:sevaexchange/l10n/l10n.dart';
import 'package:sevaexchange/models/models.dart';

class A {
  int? a;
  String? b;
}

class EditRepeatWidget<T> extends StatefulWidget {
  final T recurringModel;

  EditRepeatWidget({required this.recurringModel});

  @override
  EditRepeatWidgetState createState() => EditRepeatWidgetState();
}

class EditRepeatWidgetState extends State<EditRepeatWidget> {
  // RequestModel requestModel;
  // OfferModel offerModel;
  List<String> dayNameList = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
  List<String> daysName = [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ];
  List<String> occurenccesList = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10'
  ];

  List<bool> _selected = List.generate(7, (index) => false);
  List<int> recurringDays = [];
  DateTime selectedDate = DateTime.now();
  int endType = 0;
  String after = "";
  bool? isRecurring;
  String selectedDays = '';

  @override
  void initState() {
    super.initState();
    initialValue(
      recurring: widget.recurringModel.isRecurring ||
          widget.recurringModel.autoGenerated,
      end: widget.recurringModel.end,
      recurringDays: widget.recurringModel.recurringDays,
    );
  }

  void initialValue({
    bool? recurring,
    List<int>? recurringDays,
    End? end,
  }) {
    isRecurring = recurring;
    _selected = List.generate(
        dayNameList.length, (i) => recurringDays?.contains(i) ?? false);
    _selectOnAfter();

    endType = end?.endType == "on" ? 0 : 1;
    selectedDate = end?.endType == "on"
        ? DateTime.fromMillisecondsSinceEpoch(end!.on!.toInt())
        : DateTime.now();

    after = end?.endType == "on" ? "1" : end?.after?.toString() ?? "1";
  }

  bool viewVisible = false;
  bool titleCheck = true;

  void _handleRadioValueChange(int? value) {
    setState(() {
      endType = value ?? 0;
    });
  }

  List<int> getRecurringdays() {
    int x = 0;
    recurringDays.clear();
    for (var i = 0; i < _selected.length; i++) {
      if (_selected[i]) {
        recurringDays.add(i);
        x++;
      }
    }
    return recurringDays;
  }

  void _selectOnAfter() {
    setState(() {
      if (viewVisible) {
        viewVisible = false;
      } else {
        viewVisible = true;
      }
      titleCheck = !viewVisible;
      String days = "";
      for (int i = 0; i < 7; i++) {
        if (_selected[i]) {
          days = days + " " + daysName[i];
        }
      }
      selectedDays = days;
    });
  }

  void _cancelOnAfter() {
    setState(() {
      if (viewVisible) {
        viewVisible = false;
      } else {
        viewVisible = true;
      }
      titleCheck = !viewVisible;
    });
  }

  DateFormat dateFormat = DateFormat.yMMMd();

  Future<Null> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
        context: context,
        initialDate: selectedDate,
        firstDate: DateTime(2015, 1),
        lastDate: DateTime(2101),
        builder: (BuildContext context, Widget? child) {
          return Theme(
            data: ThemeData.light().copyWith(
              primaryColor: Colors.purple, //Head background
              colorScheme: ColorScheme.light(
                primary: Theme.of(context).primaryColor,
                secondary: Colors.purple, //selection color
              ),
              buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.primary),
              //dialogBackgroundColor: Colors.white,//Background color
            ),
            child: child!,
          );
        });
    if (picked != null && picked != selectedDate)
      setState(() {
        selectedDate = picked;
      });
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Container(
          alignment: Alignment.topLeft,
          child: Column(
            children: [
              Row(
                children: [
                  Checkbox(
                    value: isRecurring,
                    onChanged: null,
                  ),
                  Text("${S.of(context).repeat}",
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'Europa',
                        color: Colors.black,
                      )),
                  Visibility(
                    visible: isRecurring ?? false,
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(20.0, 8.0, 8.0, 8.0),
                      child: Container(
                        width: 160.0,
                        alignment: Alignment.topLeft,
                        padding: const EdgeInsets.fromLTRB(12.0, 8.0, 8.0, 8.0),
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(2.0),
                          color: Colors.black12,
                        ),
                        child: InkWell(
                            onTap: _selectOnAfter,
                            child: Text(
                                "${S.of(context).recuring_weekly_on} ${selectedDays == "" || selectedDays == " " ? "..." : selectedDays}",
                                textAlign: TextAlign.start,
                                style: TextStyle(
                                  fontSize: 14,
                                  fontFamily: 'Europa',
                                  color: Colors.black,
                                ))),
                      ),
                    ),
                  ),
                ],
              ),
              Visibility(
                visible: viewVisible,
                child: Container(
                  child: Column(
                    children: <Widget>[
                      Container(
                        alignment: Alignment.topLeft,
                        padding: const EdgeInsets.fromLTRB(12.0, 8.0, 8.0, 8.0),
                        child: Text("${S.of(context).repeat_on}",
                            textAlign: TextAlign.start,
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                              fontFamily: 'Europa',
                              color: Colors.black,
                            )),
                      ),
                      Container(
                          height: 45.0,
                          margin: EdgeInsets.fromLTRB(8.0, 8.0, 0.0, 0.0),
                          alignment: Alignment.center,
                          child: ListView.builder(
                              shrinkWrap: true,
                              itemCount: 7,
                              scrollDirection: Axis.horizontal,
                              itemBuilder: (BuildContext context, int index) =>
                                  Container(
                                      alignment: Alignment.center,
                                      height: 40.0,
                                      width: 40.0,
                                      margin: EdgeInsets.all(2.0),
                                      decoration: BoxDecoration(
                                        borderRadius:
                                            BorderRadius.circular(40.0),
                                        color: _selected[index]
                                            ? Theme.of(context).primaryColor
                                            : Colors.black12,
                                      ),
                                      child: InkWell(
                                        child: Center(
                                          child: Text(dayNameList[index],
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                fontSize: 12,
                                                fontWeight: FontWeight.bold,
                                                fontFamily: 'Europa',
                                                color: _selected[index]
                                                    ? Colors.white
                                                    : Colors.black,
                                              )),
                                        ),
                                        onTap: () => setState(() {
                                          _selected[index] = !_selected[index];
                                        }), // reverse bool value
                                      ))
//                            children: getDayList(),
                              )),
                      Container(
                        alignment: Alignment.topLeft,
                        padding:
                            const EdgeInsets.fromLTRB(12.0, 12.0, 8.0, 8.0),
                        child: Text("${S.of(context).ends}",
                            textAlign: TextAlign.start,
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                              fontFamily: 'Europa',
                              color: Colors.black,
                            )),
                      ),
                      Row(
                        children: <Widget>[
                          Radio(
                            value: 0,
                            groupValue: endType,
                            onChanged: _handleRadioValueChange,
                          ),
                          Text("${S.of(context).on}",
                              style: TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                fontFamily: 'Europa',
                                color: endType == 0
                                    ? Colors.black
                                    : Colors.black12,
                              )),
                          Container(
                            width: 160.0,
                            alignment: Alignment.topLeft,
                            margin: EdgeInsets.fromLTRB(38.0, 8.0, 8.0, 8.0),
                            padding: const EdgeInsets.fromLTRB(
                                12.0, 15.0, 12.0, 15.0),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2.0),
                              color: Colors.black12,
                            ),
                            child: InkWell(
                                onTap: endType == 0
                                    ? () async => await _selectDate(context)
                                    : null,
                                child:
                                    Text("${dateFormat.format(selectedDate)}",
                                        textAlign: TextAlign.start,
                                        style: TextStyle(
                                          fontSize: 14,
                                          fontWeight: FontWeight.bold,
                                          fontFamily: 'Europa',
                                          color: endType == 0
                                              ? Colors.black54
                                              : Colors.black12,
                                        ))),
                          )
                        ],
                      ),
                      Row(
                        children: <Widget>[
                          Radio(
                            value: 1,
                            groupValue: endType,
                            onChanged: _handleRadioValueChange,
                          ),
                          Text("${S.of(context).after}",
                              style: TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                fontFamily: 'Europa',
                                color: endType == 1
                                    ? Colors.black
                                    : Colors.black12,
                              )),
                          Container(
                            width: 160.0,
                            height: 44,
                            alignment: Alignment.topLeft,
                            margin: EdgeInsets.fromLTRB(20.0, 8.0, 8.0, 8.0),
                            padding:
                                const EdgeInsets.fromLTRB(12.0, 0.0, 12.0, 0.0),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(2.0),
                              color: Colors.black12,
                            ),
                            child: InkWell(
                                child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: <Widget>[
                                Container(
                                  child: DropdownButton(
                                    value: after,
                                    onChanged: endType == 1
                                        ? (String? Value) {
                                            setState(() {
                                              after = Value ?? after;
                                            });
                                          }
                                        : null,
                                    items: occurenccesList
                                        .map<DropdownMenuItem<String>>(
                                            (String number) {
                                      return DropdownMenuItem(
                                        value: number,
                                        child: Text(
                                          number,
                                          style: TextStyle(
                                            fontSize: 14,
                                            fontWeight: FontWeight.bold,
                                            fontFamily: 'Europa',
                                            color: endType == 1
                                                ? Colors.black54
                                                : Colors.black12,
                                          ),
                                        ),
                                      );
                                    }).toList(),
                                  ),
                                ),
                                Text("${S.of(context).occurrences}",
                                    textAlign: TextAlign.end,
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      fontFamily: 'Europa',
                                      color: endType == 1
                                          ? Colors.black54
                                          : Colors.black12,
                                    ))
                              ],
                            )),
                          )
                        ],
                      ),
                      Container(
                        margin: EdgeInsets.fromLTRB(8.0, 12.0, 8.0, 8.0),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: <Widget>[
                            Container(
                              margin: EdgeInsets.all(8.0),
                              child: InkWell(
                                onTap: _selectOnAfter,
                                child: Text("${S.of(context).done}",
                                    style: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.bold,
                                      fontFamily: 'Europa',
                                      color: Theme.of(context).primaryColor,
                                    )),
                              ),
                            ),
                            Container(
                                margin: EdgeInsets.all(8.0),
                                child: InkWell(
                                  onTap: _cancelOnAfter,
                                  child: Text("${S.of(context).cancel}",
                                      style: TextStyle(
                                        fontSize: 16,
                                        fontWeight: FontWeight.bold,
                                        fontFamily: 'Europa',
                                        color: Colors.black12,
                                      )),
                                )),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
